server:
  port: ${SERVER_PORT:8218}
  servlet.context-path: ${BASE_PATH:/}
  tomcat:
    accept-count: ${ACCEPT_COUNT:256}
    threads:
      max: ${MAX_THREADS:4}

logging:
  level: 
    root: INFO
    io:
      snap:
        scheduler: DEBUG

snap:
  scheduler:
    enabled: true
    db-polling-interval: 1m
#    datasource:
#      url: ${PG_JDBC_URL:jdbc:postgresql://localhost/snap}
#      username: ${PG_USRNAME:postgres}
#      password: ${PG_PASSWORD:root}

spring:

  #
  # Datasource configuration
  #
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${PG_JDBC_URL:jdbc:postgresql://localhost/snap}
    username: ${PG_USRNAME:postgres}
    password: ${PG_PASSWORD:root}
    hikari:
      driverClassName: org.postgresql.Driver
      connectionInitSql: SELECT 1
      minimumIdle: 1
      maximumPoolSize: 5
      connectionTimeout: 60000 
      idleTimeout: 600000 
      maxLifetime: 1800000 
      poolName: snap-pool
      autoCommit: false
      schema: ${PG_SCHEMA:public}
      