CREATE TABLE snap_lock
(
    key text NOT NULL,
	method text NOT NULL,
    lock_until timestamp with time zone NOT NULL,
    lock_at timestamp with time zone NOT NULL,
    lock_by text NOT NULL,
    CONSTRAINT snap_lock_pkey PRIMARY KEY (key,method)
);

CREATE TABLE snap_task_audit
(
	id integer GENERATED BY DEFAULT AS identity,
    key text NOT NULL,
	method text NOT NULL,
	run_on text NOT NULL,
    start_run timestamp with time zone NOT NULL,
    end_run timestamp with time zone NOT NULL,
    run_time_seconds numeric NOT NULL,
    task_error jsonb,
    CONSTRAINT snap_task_audit_pkey PRIMARY KEY (id)
);

CREATE TABLE snap_scheduler (
	name text NOT NULL,
	key text NOT NULL,
	type text NOT NULL,
	task_class text NOT NULL,
	task_data jsonb,
	task_data_class text,
	run_at timestamp with time zone NOT NULL,
	recurrence text,
	picked boolean NOT NULL DEFAULT false,
	picked_by text,
	end_run timestamp with time zone,
	CONSTRAINT snap_scheduler_pkey PRIMARY KEY (key)
);
